version: '3'
services:
  test_flask-app:
    restart: always
    image: test_app
    build: 
      context: ./flask_app
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./config/test_vars
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 3029:3019
    command: bash -c 'cd flask_app && gunicorn app:app -w 1 -b 0.0.0.0:3019 --timeout 10000 --reload'

  flask-worker1:
    image: test_app
    volumes:
      - ./:/app
    env_file:
      - ./config/test_vars
    depends_on:      
      - redis
    command: bash -c 'cd flask_app && rqworker --name worker1 --url redis://redis:6379/0'

  flask-worker2:
    image: test_app
    volumes:
      - ./:/app
    env_file:
      - ./config/test_vars
    depends_on:      
      - redis
    command: bash -c 'cd flask_app && rqworker --name worker2 --url redis://redis:6379/0'

  redis:
    image: redis
    command: redis-server --maxmemory 16000mb 

